indexer-cli/src/main/java/org/apache/maven/index/cli/NexusIndexerCli.java

Caused by the fact that the IndexSearcher obtained before indexer.scan() is called is the same one that is passed to the IndexPackingUpdate, however, once indexer.scan() is executed, the context's (directory) content is replaced with the temporay one (used for downloading) but the previously returned IndexSearcher is invalidated by the DefaultIndexingContext.openAndWarmup() method that is called for the new index directory. Any packing operation that is attempted from this point will produce an empty packed index instead of using the actual index content produced by the indexer.scan() method.
Fixed by acquireing the indexSearcher *after* the indexer.scan() method finishes, so that the pack operation works with the actual data and produces a proper packed index.

Indexing a repository with the indexer-cli (using -i and -r parameters) creates an empty packed index.

---

indexer-cli/pom.xml
indexer-core/pom.xml
indexer-core/src/test/java/org/apache/maven/index/updater/DownloadRemoteIndexerManagerTest.java
indexer-core/src/test/java/org/apache/maven/index/updater/fixtures/ServerTestFixture.java
indexer-examples/indexer-examples-spring/pom.xml
indexer-reader/pom.xml
pom.xml

W/o Lucene as it is integral part and needs bigger
changes.

[MINDEXER-134] Update dependencies

---

indexer-core/src/main/java/org/apache/maven/index/DefaultNexusIndexer.java
indexer-core/src/main/java/org/apache/maven/index/context/DefaultIndexingContext.java
indexer-core/src/main/java/org/apache/maven/index/context/MergedIndexingContext.java
indexer-core/src/main/java/org/apache/maven/index/updater/DefaultIndexUpdater.java
indexer-core/src/main/java/org/apache/maven/index/updater/WagonHelper.java
indexer-core/src/test/java/org/apache/maven/index/updater/FullBootProofOfConcept.java
indexer-reader/src/test/java/org/apache/maven/index/reader/TestSupport.java

https://issues.apache.org/jira/browse/MINDEXER-132

[MINDEXER-132] use Java 7 Files.createTempDirectory() API

---

indexer-cli/pom.xml
indexer-cli/src/main/java/org/apache/maven/index/cli/NexusIndexerCli.java
indexer-core/pom.xml

And overall fix shading warnings.

[MINDEXER-135] Fix CLI shading

---

indexer-core/pom.xml
pom.xml

And some other minor updates applied.
---
https://issues.apache.org/jira/browse/MINDEXER-138

[MINDEXER-138] Jetty scope fixed

---

indexer-core/pom.xml

Make them land in same (sub)package as core, also
remove redundant patterns.

Fix core shading

---

indexer-reader/src/main/java/org/apache/maven/index/reader/IndexReader.java

The simplest change to not disturb any possible
current users of this.
Later this will need some rework, probably with
some breaking changes.
---
https://issues.apache.org/jira/browse/MINDEXER-121

[MINDEXER-121] Prevent ChunkReadIterator leak

---

indexer-reader/pom.xml

To make build reproducible
---
https://issues.apache.org/jira/browse/MINDEXER-159

[MINDEXER-159] Update m-bundle-p

---

indexer-examples/indexer-examples-spring/pom.xml
pom.xml

Update spring (used in demos) and
plexus-utils (coming as transitive).
---
https://issues.apache.org/jira/browse/MINDEXER-160

[MINDEXER-160] Update spring and p-u

---

indexer-examples/indexer-examples-spring/pom.xml
pom.xml

Changes:
* resolver to 1.8.1
* maven to 3.8.6
* spring (in examples) to 5.3.21
---
https://issues.apache.org/jira/browse/MINDEXER-163

[MINDEXER-163] Update dependencies

---

indexer-examples/src/site/site.xml
indexer-reader/src/site/site.xml
search-api/src/site/site.xml
search-backend-indexer/src/site/site.xml
search-backend-smo/src/site/site.xml

JIRA: https://issues.apache.org/jira/browse/MINDEXER-155
@slawekjaranowski

[MINDEXER-155] Add Maven site descriptor for all modules

---

indexer-reader/src/main/java/org/apache/maven/index/reader/RecordCompactor.java
indexer-reader/src/main/java/org/apache/maven/index/reader/RecordExpander.java

https://issues.apache.org/jira/browse/MINDEXER-165

[MINDEXER-165] Have RecordCompactor and RecordExpander implement Function

---

indexer-core/src/main/java/org/apache/maven/index/artifact/Gav.java
indexer-core/src/main/java/org/apache/maven/index/artifact/M2GavCalculator.java
indexer-core/src/test/java/org/apache/maven/index/artifact/M2GavCalculatorTest.java

Adds support for .sha256 and .sha512 checksum files

MINDEXER-171 Support SHA256 and SHA512 HashType

---

pom.xml

Updates to dependencies:
* Lucene 9.4.2
Updates to plugins:
* modernizer 2.5.0
---
https://issues.apache.org/jira/browse/MINDEXER-177 
https://issues.apache.org/jira/browse/MINDEXER-178

[MINDEXER-177][MINDEXER-178] Update Lucene and modernizer

---

pom.xml

Still 2.x were used.
---
https://issues.apache.org/jira/browse/MINDEXER-179

[MINDEXER-179] Update install/deploy

---

pom.xml

--
https://issues.apache.org/jira/browse/MINDEXER-180

[MINDEXER-180] Upgrade to Maven Resolver 1.9.2

---

pom.xml

Update build plugins:
* m-install-p 3.1.1
* m-deploy-p 3.1.1
* modernizer-m-p 2.6.0
* m-surefire-p 3.0.0
Also adjust build requirements:
* Java latest LTS (17.0.6+)
* Maven latest maintained (3.8.7+)
---
https://issues.apache.org/jira/browse/MINDEXER-186

[MINDEXER-186] Update build

---

pom.xml

Update dependencies:
* resolver 1.9.10
* maven 3.9.1
* slf4j 2.0.7
* plexus-utils 3.5.1
---
https://issues.apache.org/jira/browse/MINDEXER-187

[MINDEXER-187] Update dependencies

---

indexer-reader/pom.xml

Changes:
* maven-bundle-plugin 5.1.9
---
https://issues.apache.org/jira/browse/MINDEXER-192

[MINDEXER-192] Update build plugins

---

indexer-core/src/main/java/org/apache/maven/index/AbstractSearchRequest.java
indexer-core/src/main/java/org/apache/maven/index/AbstractSearchResponse.java
indexer-core/src/main/java/org/apache/maven/index/IteratorSearchResponse.java
indexer-core/src/main/java/org/apache/maven/index/QueryCreator.java
indexer-core/src/main/java/org/apache/maven/index/UniqueGAArtifactFilterPostprocessor.java
indexer-core/src/main/java/org/apache/maven/index/context/UnsupportedExistingLuceneIndexException.java
pom.xml

And fix some warnings emitted by compiler.
---
https://issues.apache.org/jira/browse/MINDEXER-194

[MINDEX-194] Update to parent POM 40

---

pom.xml

Lucene 9.7.0
---
https://issues.apache.org/jira/browse/MINDEXER-196

[MINDEXER-196] Update Lucene 9.7.0

---

indexer-core/src/main/java/org/apache/maven/index/artifact/M2GavCalculator.java
indexer-core/src/main/java/org/apache/maven/index/context/DefaultIndexingContext.java
indexer-core/src/main/java/org/apache/maven/index/expr/StringSearchExpression.java
indexer-reader/src/main/java/org/apache/maven/index/reader/RecordExpander.java

General update, minor.
This commit does not introduce semantic change, merely updates code to Java 11.

trim vs blank

---

pom.xml

---
https://issues.apache.org/jira/browse/MINDEXER-197

[MINDEXER-197] Update modernizer plugin

---

pom.xml

---
https://issues.apache.org/jira/browse/MINDEXER-200 https://issues.apache.org/jira/browse/MINDEXER-201

[MINDEXER-200][MINDEXER-201] Update Lucene to 9.8.0, Maven 3.9.5

---

search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/RemoteRepositorySearchBackendFactory.java
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/SmoSearchBackendFactory.java
search-backend-smo/src/test/java/org/apache/maven/search/backend/smo/internal/SmoSearchBackendImplTest.java

Make them both static helpers, as they have no logic.
---
https://issues.apache.org/jira/browse/MINDEXER-205

[MINDEXER-205] Align Search API backend factories

---

search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/internal/RemoteRepositorySearchBackendImpl.java
search-backend-remoterepository/src/test/java/org/apache/maven/search/backend/remoterepository/internal/RemoteRepositorySearchBackendImplTest.java

---
https://issues.apache.org/jira/browse/MINDEXER-207

[MINDEXER-207] Handle HTTP 404 gracefully

---

indexer-cli/pom.xml
indexer-core/pom.xml
indexer-examples/indexer-examples-basic/pom.xml
indexer-reader/pom.xml
pom.xml
search-api/pom.xml
search-backend-indexer/pom.xml
search-backend-remoterepository/pom.xml
search-backend-smo/pom.xml

Updated to 3.9.9, 1.9.22 and 3.0
---
https://issues.apache.org/jira/browse/MINDEXER-240

[MINDEXER-240] Maven, Resolver, Hamcrest

---

search-api/src/main/java/org/apache/maven/search/api/transport/Java11HttpClientTransport.java

Slightly improve it, at least give some hint from where and what we got. note: Java 11 HttpClient does NOT expose reason phrase
---
https://issues.apache.org/jira/browse/MINDEXER-239

[MINDEXER-239] Better HTTP error messages

---

.github/dependabot.yml
.github/workflows/maven-verify.yml
indexer-cli/pom.xml
indexer-core/pom.xml
indexer-examples/indexer-examples-basic/pom.xml
indexer-examples/indexer-examples-basic/src/main/java/org/apache/maven/index/examples/BasicUsageExample.java
indexer-examples/indexer-examples-spring/pom.xml
pom.xml
search-backend-indexer/pom.xml

And perform some cleanup. Also, there should be a followup as new modernizer cryes over indexer-core and indexer-cli codebase.
---
https://issues.apache.org/jira/browse/MINDEXER-251

[MINDEXER-251] Parent 44

---

indexer-examples/pom.xml
indexer-reader/src/test/java/org/apache/maven/index/reader/CachingResourceHandler.java
indexer-reader/src/test/java/org/apache/maven/index/reader/ChunkReaderTest.java
indexer-reader/src/test/java/org/apache/maven/index/reader/DirectoryResourceHandler.java
indexer-reader/src/test/java/org/apache/maven/index/reader/HttpResourceHandler.java
indexer-reader/src/test/java/org/apache/maven/index/reader/IndexReaderTest.java
indexer-reader/src/test/java/org/apache/maven/index/reader/TestSupport.java
indexer-reader/src/test/java/org/apache/maven/index/reader/TransformTest.java
pom.xml
search-backend-indexer/src/test/java/org/apache/maven/search/backend/indexer/internal/IndexerCoreSearchBackendImplTest.java

For the rest see MINDEXER-252
---
https://issues.apache.org/jira/browse/MINDEXER-255

[MINDEXER-255] fix relevant codebase modernizer issues

---

indexer-cli/src/site/site.xml
indexer-core/src/site/site.xml
indexer-examples/indexer-examples-basic/src/site/site.xml
indexer-examples/indexer-examples-spring/src/site/site.xml
indexer-examples/src/site/site.xml
indexer-reader/src/site/site.xml
search-api/src/site/site.xml
search-backend-indexer/src/site/site.xml
search-backend-remoterepository/src/site/site.xml
search-backend-smo/src/site/site.xml
src/site/site.xml

Better late then never.
---
https://issues.apache.org/jira/browse/MINDEXER-256

[MINDEXER-256] Update site descriptors
