indexer-core/src/main/java/org/apache/maven/index/context/IndexUtils.java

While trying to write an IndexCreator, I`ve discovered that the ArtifactInfo instance that I received in the IndexCreator.updateDocument method was improperly constructed.
Digging further, I discovered that the updateDocument method is called by IndexUtils.updateDocument that, in turn, constructs its ArtifactInfo instance by calling IndexUtils.constructArtifactInfo(doc, context).
It turns out that the IndexUtils.constructArtifactInfo method uses the no-arguments constructor for creating an ArtifactInfo instance and relies on the IndexCreators to populate it. However, **it does not set the repositoryId or contextId fields on this new instance**, leaving it in an inconsistent state (with values for the artifact, but without the ability to properly identify the artifact, i.e. where it comes …

Add minimal information to a newly created artifact info (using the IndexUtils method), linking it to the context it belongs to.

---

indexer-core/pom.xml

There are classes included in the shaded_lucene jar file from dependent artifacts. To avoid conflicts with other packages and their maven dependencies there should only be the relocated packages and the maven indexer packages in the jar.
Dependencies that are not relocated should be still loaded via the dependent jar files.

Excluding additional dependencies from shaded jar

---

indexer-core/pom.xml

Found an issue with referenced objects in maven model packages in the shaded library (references to classes in a shaded package that does not exist). I think this update should fix it.

Removing shading for maven model packages

---

pom.xml

fixes warnings
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.apache.maven.indexer:maven-indexer:pom:6.0.1-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.scope' for ch.qos.logback:logback-classic:jar must be one of [provided, compile, runtime, test, system, import] but is 'optional'. @ line 118, column 16
[WARNING] 'dependencyManagement.dependencies.dependency.scope' for ch.qos.logback:logback-core:jar must be one of [provided, compile, runtime, test, system, import] but is 'optional'. @ line 124, column 16
[WARNING] 'dependencyManagement.dependencies.dependency.scope' for org.slf4j:jcl-over-slf4j:jar must be one of [provided, compile, runtime, test, system, import] but is 'optional'. @ line 132, column 16
[WARNING]
```

Correct errors with optional scope in dependency

---

indexer-core/src/main/java/org/apache/maven/index/DefaultQueryCreator.java
indexer-core/src/main/java/org/apache/maven/index/NexusIndexer.java
indexer-core/src/main/java/org/apache/maven/index/treeview/DefaultIndexTreeView.java
indexer-core/src/test/java/org/apache/maven/index/DefaultIndexNexusIndexerTest.java
indexer-core/src/test/java/org/apache/maven/index/FullIndexNexusIndexerTest.java
indexer-core/src/test/java/org/apache/maven/index/Nexus13NexusIndexerTest.java
indexer-core/src/test/java/org/apache/maven/index/Nexus3881NexusIndexerTest.java
indexer-core/src/test/java/org/apache/maven/index/NexusIndexerTest.java
indexer-core/src/test/java/org/apache/maven/index/SearchWithAnEmptyIndexTest.java
indexer-core/src/test/java/org/apache/maven/index/creator/OsgiArtifactIndexCreatorTest.java
indexer-core/src/test/resources/testQueryCreatorNGSearch/case01.txt
indexer-core/src/test/resources/testQueryCreatorNGSearch/case05.txt
indexer-examples/indexer-examples-basic/src/main/java/org/apache/maven/indexer/examples/BasicUsageExample.java
indexer-examples/indexer-examples-spring/src/main/java/org/apache/maven/indexer/examples/indexing/RepositoryIndexer.java

Remove deprecated usages of BooleanQuery constructor - use Builder
Based on Sopot Cela changes

[MINDEXER-115] Migrate to BooleanQuery.Builder

---

indexer-examples/indexer-examples-basic/src/main/java/org/apache/maven/indexer/examples/BasicUsageExample.java

Fixes:
```bash
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.maven.indexer.examples.BasicUsageExampleTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.914 s <<< FAILURE! - in org.apache.maven.indexer.examples.BasicUsageExampleTest
[ERROR] testApp(org.apache.maven.indexer.examples.BasicUsageExampleTest)  Time elapsed: 0.886 s  <<< ERROR!
java.io.IOException: Transfer for nexus-maven-repository-index.properties failed; Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties from http://repo1.maven.org/maven2/.index/nexus-maven-repository-index.prop …
```

Change http to https

---

indexer-core/src/main/java/org/apache/maven/index/treeview/AbstractTreeNode.java

(doc) Fix spurious javadoc @param tag

---

indexer-core/src/main/java/org/apache/maven/index/context/DefaultIndexingContext.java
indexer-examples/indexer-examples-spring/src/main/java/org/apache/maven/index/examples/indexing/RepositoryIndexerFactory.java

DefaultIndexingContext invokes method setIndexDirectoryFile two times (if indexDirectory set): once with null and once with given indexDirectory.
In first case, ID is used to create temp directory, just to have 2nd invocation use passed in directory (and leave temp directory created in 1st invocation alone).
This bug, in relation to commit 019edb7ff87a505372ad4f469c1b2a6c9d4ae292 broke Spring examples, as it seems Spring example contained a typo since beginning: it uses "/" (slash) in context ID.
Files.createTempDirectory fails if prefix contains path separator.
---
https://issues.apache.org/jira/browse/MINDEXER-140

[MINDEXER-140] Fix double invocation of DefaultIndexingContext.setIndexDirectoryFile

---

indexer-core/pom.xml
indexer-core/src/main/java/org/apache/maven/index/creator/MavenPluginArtifactInfoIndexCreator.java
indexer-core/src/main/java/org/apache/maven/index/updater/WagonHelper.java
indexer-core/src/test/java/org/apache/maven/index/updater/DefaultIndexUpdaterEmbeddingIT.java
indexer-core/src/test/java/org/apache/maven/index/updater/DownloadRemoteIndexerManagerTest.java
indexer-core/src/test/java/org/apache/maven/index/updater/FullBootProofOfConcept.java
pom.xml

Plexus is not needed anymore for indexer, while
it retains all the functionalities. WagonHelper is
modified to use Injector instead.
Still, plexus is used in UTs/ITs, hence it is
present but only in test scope, as all the "injected
tests" are plexus based, hence redoing that is
much bigger effort.
---
https://issues.apache.org/jira/browse/MINDEXER-139

[MINDEXER-139] Decouple from Plexus

---

indexer-examples/indexer-examples-spring/pom.xml
pom.xml

Updates:
* parent POM to 36
* Maven to 3.8.5
* Resolver to 1.8.0
* logback to 1.2.11
* test/guava to 31
* examples/spring to 5.3.19
Build:
* surefire to 3.0.0-M6
* checkstyle (m-checkstyle-p dependency) to 9.3
---
Obsoletes https://github.com/apache/maven-indexer/pull/185
https://issues.apache.org/jira/browse/MINDEXER-145

[MINDEXER-145] Update parent POM and dependencies

---

indexer-core/src/main/java/org/apache/maven/index/DefaultArtifactContextProducer.java
indexer-core/src/main/java/org/apache/maven/index/artifact/M2GavCalculator.java
indexer-core/src/test/java/org/apache/maven/index/artifact/M2GavCalculatorTest.java

Scanner throws IOOBEx when scanning local repository
due GAV level locally installed metadata. Filter it
out better (m2gav calculator and context producer).
Added UT that initially reproduced the issue, and now
passes OK.
---
https://issues.apache.org/jira/browse/MINDEXER-144

[MINDEXER-144] IOOBEx on GAV local metadata

---

indexer-core/src/main/java/org/apache/maven/index/context/DefaultIndexingContext.java
indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataReader.java
indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataWriter.java
indexer-core/src/test/java/org/apache/maven/index/AbstractNexusIndexerTest.java
indexer-core/src/test/java/org/apache/maven/index/ConcurrentUseWithMergedContextTest.java
indexer-core/src/test/java/org/apache/maven/index/DuplicateSearchTest.java
indexer-core/src/test/java/org/apache/maven/index/Nexus13NexusIndexerTest.java
indexer-core/src/test/java/org/apache/maven/index/Nexus3177HitLimitChecks.java
indexer-core/src/test/java/org/apache/maven/index/NexusIndexerTest.java
indexer-core/src/test/java/org/apache/maven/index/context/TrackingLockFactoryTest.java
indexer-core/src/test/java/org/apache/maven/index/updater/DefaultIndexUpdaterTest.java
indexer-core/src/test/java/org/apache/maven/index/updater/IndexDataTest.java

There were several "sloppy" spots especially about indexing
options and norms (field type options), that are now
fixed. Also, replaced uses of deprecated RAMDirectory with
new ByteBuffersDirectory, that affects only test code.
---
https://issues.apache.org/jira/browse/MINDEXER-146

[MINDEXER-146] Fix issues reported by Lucene 9

---

indexer-core/src/main/java/org/apache/maven/index/context/DefaultIndexingContext.java
indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataReader.java
indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataWriter.java
indexer-core/src/test/java/org/apache/maven/index/packer/NEXUS4149TransferFormatTest.java

Do not (mis)use Lucene index to store potentially huge
dataset, while this field is really not even searched, it
just contains aggregated artifact groups that are present
on index.
---
https://issues.apache.org/jira/browse/MINDEXER-147

[MINDEXER-147] Move allGroups/rootGroups to in memory only

---

indexer-core/src/main/java/org/apache/maven/index/updater/DefaultIndexUpdater.java

The order or the last two arguments of the call to
IndexingContext#replace should be "allGroups, rootGroups", but is
called as "rootGroups, allGroups", leading to the wrong contents
of the corresponding fields of the IndexingContext.

[MINDEXER-157] After import all groups and root groups are inverted in the IndexingContext

---

.github/workflows/maven-verify.yml
Jenkinsfile
indexer-cli/src/test/java/org/apache/maven/index/cli/AbstractNexusIndexerCliTest.java
indexer-core/src/main/java/org/apache/maven/index/updater/DefaultIndexUpdater.java
indexer-core/src/test/java/org/apache/maven/index/NexusIndexerTest.java
indexer-reader/src/test/java/org/apache/maven/index/reader/TestUtils.java
pom.xml
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/internal/Java11HttpClientSmoSearchTransport.java
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/internal/SmoSearchBackendImpl.java
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/internal/UrlConnectionSmoSearchTransport.java

Changes:
- requires latest Java LTS to build
- requires latest Maven to build
- uses `--release` to set Java 11 level
- drop animal sniffer as JDK does all now
The goal is to keep project stick to latest LTS Java, latest Maven
and then target the required Java level using new release switch.
---
https://issues.apache.org/jira/browse/MINDEXER-161

[MINDEXER-161] Make project Java 11

---

indexer-core/pom.xml
pom.xml

Now that indexer is Java11, upgrade to latest Lucene can happen.
---
https://issues.apache.org/jira/browse/MINDEXER-162

[MINDEXER-162] Update Lucene to 9.2

---

indexer-core/src/main/java/org/apache/maven/index/DefaultArtifactContextProducer.java
indexer-core/src/main/java/org/apache/maven/index/artifact/M2GavCalculator.java
indexer-core/src/test/java/org/apache/maven/index/artifact/M2GavCalculatorTest.java

This is a follow-up on https://github.com/apache/maven-indexer/pull/198 and [MINDEXER-144](https://issues.apache.org/jira/browse/MINDEXER-144), which only fixed the IndexOutOfBound issues for some file types.
The exception can still happen if the local repository contains `_remote.repository` or similar files. Apparently, with Maven 3.0.x, maven creates these file to record where the file was resolved from ([source](https://stackoverflow.com/a/16870552/3388748)).
<details>
<summary>Full stacktrace for reference:</summary>
```
Caused by: java.lang.IndexOutOfBoundsException: start 56, end 64, length 57
at java.base/java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1794)
at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:675)
at …
```

[MINDEXER-164] Fix IOOBEx on GAV remote repositories

---

indexer-cli/pom.xml

For simplicity sake, the shaded CLI
executable JAR will have a classifier,
instead to replace the main artifact.
This implies GAV of CLI will change,
so is on hold until next major release.
---
https://issues.apache.org/jira/browse/MINDEXER-148

[MINDEXER-148] Do not replace CLI

---

indexer-reader/pom.xml
indexer-reader/src/main/java/org/apache/maven/index/reader/ChunkReader.java
indexer-reader/src/main/java/org/apache/maven/index/reader/ChunkWriter.java
indexer-reader/src/main/java/org/apache/maven/index/reader/IndexReader.java
indexer-reader/src/main/java/org/apache/maven/index/reader/IndexWriter.java
indexer-reader/src/main/java/org/apache/maven/index/reader/Record.java
indexer-reader/src/main/java/org/apache/maven/index/reader/RecordCompactor.java
indexer-reader/src/main/java/org/apache/maven/index/reader/RecordExpander.java
indexer-reader/src/main/java/org/apache/maven/index/reader/ResourceHandler.java
indexer-reader/src/main/java/org/apache/maven/index/reader/Utils.java
indexer-reader/src/main/java/org/apache/maven/index/reader/WritableResourceHandler.java
indexer-reader/src/main/java/org/apache/maven/index/reader/resource/BufferedResource.java
indexer-reader/src/main/java/org/apache/maven/index/reader/resource/BufferedResourceHandler.java
indexer-reader/src/main/java/org/apache/maven/index/reader/resource/BufferedWritableResourceHandler.java
indexer-reader/src/main/java/org/apache/maven/index/reader/resource/PathWritableResource.java
indexer-reader/src/main/java/org/apache/maven/index/reader/resource/PathWritableResourceHandler.java
indexer-reader/src/main/java/org/apache/maven/index/reader/resource/UriResourceHandler.java
indexer-reader/src/test/java/org/apache/maven/index/reader/CachingResourceHandler.java
indexer-reader/src/test/java/org/apache/maven/index/reader/ChunkReaderTest.java
indexer-reader/src/test/java/org/apache/maven/index/reader/DirectoryResourceHandler.java
indexer-reader/src/test/java/org/apache/maven/index/reader/HttpResourceHandler.java
indexer-reader/src/test/java/org/apache/maven/index/reader/IndexReaderTest.java
indexer-reader/src/test/java/org/apache/maven/index/reader/IndexWriterTest.java
indexer-reader/src/test/java/org/apache/maven/index/reader/TestSupport.java
indexer-reader/src/test/java/org/apache/maven/index/reader/TestUtils.java
indexer-reader/src/test/java/org/apache/maven/index/reader/TransformTest.java
pom.xml

For now remove the not-so-helpful generic that was bad, update Javadoc... Let's see for more later. Also remove uused Guava. Biggest change: no "resource" is auto closed, it is all responsibility of code using reader.
---
https://issues.apache.org/jira/browse/MINDEXER-152

[MINDEXER-152] Simplify/rework IndexReader API

---

indexer-cli/src/main/java/org/apache/maven/index/cli/NexusIndexerCli.java
indexer-core/src/main/java/org/apache/maven/index/updater/DefaultIndexUpdater.java
indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataReader.java
indexer-core/src/main/java/org/apache/maven/index/updater/IndexUpdateRequest.java
indexer-core/src/test/java/org/apache/maven/index/updater/IndexDataTest.java
indexer-examples/indexer-examples-basic/src/main/java/org/apache/maven/index/examples/BasicUsageExample.java
search-backend-indexer/src/test/java/org/apache/maven/search/backend/indexer/internal/IndexerCoreSearchBackendImplTest.java

Introduce MT index update, allow users to specify the count of threads/silos to use while importing index. Without code change threads = 1 and there is no change in codepath (everything works as before).
This change (ingesting GZIP files raw records into Lucene index on multiple threads) on my PC halves the execution time: while BasicUsageExample on master takes over 15 minutes to finish (when doing full update), this PR makes it under 7 minutes when using 4 threads.
---
https://issues.apache.org/jira/browse/MINDEXER-151

[MINDEXER-151] Speed up Index update from remote

---

search-api/pom.xml
search-backend-indexer/src/main/java/org/apache/maven/search/backend/indexer/IndexerCoreSearchBackendFactory.java
search-backend-indexer/src/test/java/org/apache/maven/search/backend/indexer/internal/IndexerCoreSearchBackendImplTest.java
search-backend-smo/pom.xml
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/SmoSearchBackend.java
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/SmoSearchBackendFactory.java
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/SmoSearchTransportSupport.java
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/internal/SmoSearchBackendImpl.java
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/internal/SmoSearchTransportProvider.java
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/internal/SmoSearchTransportSupplier.java
search-backend-smo/src/main/java/org/apache/maven/search/backend/smo/internal/UrlConnectionSmoSearchTransport.java
search-backend-smo/src/main/java11/org/apache/maven/search/backend/smo/internal/Java11HttpClientSmoSearchTransport.java
search-backend-smo/src/main/java11/org/apache/maven/search/backend/smo/internal/SmoSearchTransportProvider.java
search-backend-smo/src/main/java11/org/apache/maven/search/backend/smo/internal/SmoSearchTransportSupplier.java
search-backend-smo/src/test/java/org/apache/maven/search/backend/smo/internal/SmoSearchBackendImplTest.java

There is nothing special with them, but provide
alt transport for Java11. The Indexer backend MUST be Java11 as it directly uses Indexer that is Java11.
---
https://issues.apache.org/jira/browse/MINDEXER-173

[MINDEXER-173] Make Search API and SMO backend Java8

---

indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataReader.java

The MT updater did not clean up silos after done.
---
https://issues.apache.org/jira/browse/MINDEXER-176

[MINDEXER-176] Clean up silos

---

indexer-examples/pom.xml

They are really just source examples, are waste of bytes to deploy them to MC.
---
https://issues.apache.org/jira/browse/MINDEXER-175

[MINDEXER-175] Do not deploy examples

---

indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataReader.java

Noticed that both, the single threaded and the multi threaded impl used CHMs. Instead of only changing `readIndexST` to plain `Map`s, I switched everything to `Set`s.
---
https://issues.apache.org/jira/browse/MINDEXER-181

[MINDEXER-181] IndexDataReader should use Sets

---

.github/workflows/maven-verify.yml
indexer-cli/pom.xml
indexer-examples/indexer-examples-spring/pom.xml
indexer-examples/indexer-examples-spring/src/main/java/org/apache/maven/index/examples/indexing/RepositoryIndexerFactory.java
pom.xml
search-backend-smo/pom.xml

Updates:
* lucene to 9.5.0
* slf4j for 2.0.6
* maven to 3.8.7
* resolver to 1.9.4
* (search-smo) gson to 2.10.1
* (build) surefire to 3.0.0-M8
* (examples) springframework to 5.3.25 (and fix example, it was broken)
---
https://issues.apache.org/jira/browse/MINDEXER-183

[MINDEXER-183] Upgrade key dependencies

---

pom.xml

Indexer uses Version from resolver, and 1.9.5 carries important fixes related to sorting some peculiar versions.
---
https://issues.apache.org/jira/browse/MINDEXER-184

[MINDEXER-184] Update resolver to 1.9.5

---

indexer-core/src/main/java/org/apache/maven/index/updater/DefaultIndexUpdater.java
indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataReader.java
indexer-core/src/main/java/org/apache/maven/index/updater/IndexUpdateRequest.java

this is a draft to start a discussion, it does two things:
- uses `IndexUpdateRequest` as configuration for `IndexDataReader` (tmp folder, factory etc)
- moves the filtering from post extraction to the read phase
- makes filtering really fast (and multi threaded too), it is no longer an extra step
- has actually an effect on the on-disk index size (since I've learned lucene doesn't really remove things since all files are immutable)
I do realize that this is not quite the same behavior as before. To retain the exact same behavior, we could add this as additional filter, one during read (new), one after extraction (old). (edit: done, see second commit)
example filter:
```java
final Instant cutoff = ZonedDateTime.now().minusYears(2).toInstant();
iur.setExtractionFilter((doc) -> { …
```

filter in index reader and use update request for configuration

---

.gitignore
indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataReader.java
pom.xml

The consumer Threads can quit early when an exception occurs. In that case the consumer will usually block on `put` once the queue is full without a chance to recover.
This change clears the queue and shuts the executor service down as soon an exception is caught.
fixes: https://issues.apache.org/jira/browse/MINDEXER-188

[MINDEXER-188] Ensure that the producer thread doesn't indefinitely block on the queue

---

indexer-core/src/main/java/org/apache/maven/index/creator/MinimalArtifactInfoIndexCreator.java
indexer-core/src/main/java/org/apache/maven/index/updater/IndexDataReader.java

- async-profiler showed two optimization opportunities in the index creation code
- IndexDataReader can avoid some work by moving an if-check up
- `split` can be replaced by `indexOf` + `substring` pairs
- this reduces MT extraction time from ~328s to ~303s on my machine (i6700k)
---
https://issues.apache.org/jira/browse/MINDEXER-190
---

[MINDEXER-190] Avoid using String#split in hot code if possible

---

indexer-core/src/main/java/org/apache/maven/index/context/DefaultIndexingContext.java
indexer-core/src/main/java/org/apache/maven/index/context/IndexingContext.java
indexer-core/src/main/java/org/apache/maven/index/context/MergedIndexingContext.java
indexer-core/src/main/java/org/apache/maven/index/updater/DefaultIndexUpdater.java
indexer-core/src/test/java/org/apache/maven/index/updater/DefaultIndexUpdaterTest.java

Rebuilding of the in-memory group data takes more time than the index update itself since it has to iterate through the full index.
What is worse is that rebuilding happens in a [loop](https://github.com/apache/maven-indexer/blob/fbf7c0c7d305756092ba93e40d77c0a3f0ce7eab/indexer-core/src/main/java/org/apache/maven/index/updater/DefaultIndexUpdater.java#L568-L570) for each chunk:
https://github.com/apache/maven-indexer/blob/fbf7c0c7d305756092ba93e40d77c0a3f0ce7eab/indexer-core/src/main/java/org/apache/maven/index/updater/DefaultIndexUpdater.java#L428-L430
The reader has all group data of the extracted incremental update already, while the context should have the group data of the current index.
If we assume that maven group IDs are rarely removed we can simply merge both collections without …

[MINDEXER-191] Avoid group rebuilding during incremental updates

---

indexer-examples/indexer-examples-spring/pom.xml
pom.xml

Changes:
* spring 5.3.27 (demos)
* javax.annotation-api 1.3.2 (demos)
* sisu 0.9.0.M2
* ~resolver 1.9.11~ no need for this
* jetty 9.4.51 (test)
---
https://issues.apache.org/jira/browse/MINDEXER-193

[MINDEXER-193] Update dependencies

---

search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/Context.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/RecordFactory.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/RemoteRepositorySearchBackendFactory.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/ResponseExtractor.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/extractor/MavenCentralResponseExtractor.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/extractor/Nx2ResponseExtractor.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/extractor/ResponseExtractorSupport.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/internal/RemoteRepositorySearchBackendImpl.java
search-backend-remoterepository/src/test/java/org/apache/maven/search/backend/remoterepository/internal/RemoteRepositorySearchBackendImplTest.java

RAO is powered by Nx2 that emits DIFFERENT structured HTML than Maven Central, hence HTML parsing is slightly different.
"exploded" bits to be able to provide different extractors and now RR supports Maven Central and Nx2 remote repositories.
---
https://issues.apache.org/jira/browse/MINDEXER-195

[MINDEXER-195] RAO support for RR backend

---

indexer-cli/pom.xml
indexer-examples/indexer-examples-spring/pom.xml
pom.xml
search-backend-remoterepository/pom.xml

- lucene 9.8.0 to 9.9.0 changes: https://lucene.apache.org/core/9_9_0/changes/Changes.html
- this also switches javac source/target to release
- didn't touch guice since it 7.0 changes namespace

Apache Lucene 9.9.0 and other minor dependency bumps

---

pom.xml
search-backend-indexer/pom.xml

Changes:
* update Guava to 32.1.3-jre
* get rid of Java21+ warning (Sisu APT)
* hamcrest-core 1.3 still lurking somewhere, just up it
* fix scope of Sisu in a module
---
https://issues.apache.org/jira/browse/MINDEXER-210
https://issues.apache.org/jira/browse/MINDEXER-211

[MINDEXER-210][MINDEXER-211] Guava 32.1.3-jre and cleanup

---

indexer-core/src/main/java/org/apache/maven/index/ArtifactContext.java

`DefaultScanner` is processing all files which are in the local repo, which means that `ArtifactContext` has to deal with files which are no zip archives too.
This updates `ArtifactContext` to not log zip exceptions as warning if it can't open the zip but should still log all other exceptions which might occur after successful initial read.
for example log see: https://github.com/apache/netbeans/issues/6756 (it uses a different scanner impl but `DefaultScanner` does even less filtering so the result should be the same)

ArtifactContext should not log warnings if artifacts are no zip files.

---

pom.xml

And (build) surefire to 3.2.5 should come from parent.
---
https://issues.apache.org/jira/browse/MINDEXER-223

[MINDEXER-223] Update SLF4J to 2.0.13

---

search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/RecordFactory.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/extractor/MavenCentralResponseExtractor.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/extractor/Nx2ResponseExtractor.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/extractor/ResponseExtractorSupport.java
search-backend-remoterepository/src/main/java/org/apache/maven/search/backend/remoterepository/internal/RemoteRepositorySearchBackendImpl.java
search-backend-remoterepository/src/test/java/org/apache/maven/search/backend/remoterepository/internal/RemoteRepositorySearchBackendImplTest.java

And fill it in Record.
---
https://issues.apache.org/jira/browse/MINDEXER-222

[MINDEXER-222] RR backend in case of GAVCE search should reuse LastModified HTTP header
